name:                hssearch
version:             0.1.0.0
github:              "clarkcb/xsearch"
license:             MIT
author:              "Cary Clark"
maintainer:          "clarkcb@gmail.com"
copyright:           "2021 Cary Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            File search utility in Haskell
# category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/clarkcb/xsearch#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- directory
- filepath
- regex-pcre-builtin >=0.95.2
- split >=0.2.3
- text
- time
- timeit >=2.0
- unordered-containers
- vector
- hsfind

data-files:
  - data/*.json

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hssearch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssearch

tests:
  hssearch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hssearch
    - HUnit >=1.6 && <1.7
    - test-framework >=0.8 && <0.9
    - test-framework-hunit >=0.3 && <0.4
