#!/bin/bash

SCRIPTPATH=$(readlink "${BASH_SOURCE[0]}")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

CONFIGURATION=debug
#CONFIGURATION=release
CMAKE_BUILD_DIR=$SCRIPTDIR/cmake-build-$CONFIGURATION
CPPSEARCHEXE=$CMAKE_BUILD_DIR/cppsearch

$CPPSEARCHEXE "$@"
