/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
    id("maven-publish")
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(libs.commons.io)
    implementation(libs.org.json)
    implementation("ktfind:lib:0.1.0-SNAPSHOT")
    testImplementation(libs.junit.jupiter)
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.release = 17
}

group = "ktsearch" // should this be "ktsearch" or "xsearch.ktsearch"?
version = "0.1.0-SNAPSHOT"

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["kotlin"])
        }
    }
    repositories {
        mavenLocal()
    }
}
