//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsSearch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bz2 cpio ear gz hqx jar pax rar sit sitx tar tgz war zip Z")]
        public string CompressedExtensions {
            get {
                return ((string)(this["CompressedExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ai bin class com dat dbmdl dcr dir dll dxr dms doc docx dot exe hlp indd lnk mo o" +
            "bj pdb ppt psd pyc pyo qxd so swf sys vsd xls xlsx xlt")]
        public string BinaryExtensions {
            get {
                return ((string)(this["BinaryExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 am app as asc ascx asm asp aspx bash bat bdsproj bsh c cc cfg clj cls cmd cnt conf config cpp cs csh cshtml csproj css csv ctl dat dbproj dbml dbschema ddl dep dfm disco dlg dof dpr dsp dsw dtd env etx exp fls fs fsproj h hpp htm html ics iml in inc ini ipr iws java js jsp layout log mak map master mht mxml pas php php3 pl plist pm po properties py rb rc rc2 rdf resx rex rtf rtx scala scc sgm sgml sh sln smi smil spec sqc sql st str strings suml svg sxw t tcl tld tmx tsv txt url user vb vbproj vbs vcf vcproj vdproj vm vrml vssscc vxml wbxml webinfo wml wmls wrl wsd wsdd wsdl xlf xml xsd xsl xslt")]
        public string TextExtensions {
            get {
                return ((string)(this["TextExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aif aifc aiff au avi bmp cab dat db dmg eps gif ico idlk ief iso jpe jpeg jpg m3u" +
            " m4a m4p mov movie mp3 mp4 mpe mpeg mpg mxu ogg pdf pict png ps qt ra ram rm rpm" +
            " scc snd suo tif tiff wav")]
        public string NoSearchExtensions {
            get {
                return ((string)(this["NoSearchExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("adm aps cli clw def df2 ncb nt nt2 orig pc plg roff sun t tex texinfo tr xwd")]
        public string UnknownExtensions {
            get {
                return ((string)(this["UnknownExtensions"]));
            }
        }
    }
}
