class String
  def black: () -> ::String

  def red: () -> ::String

  def green: () -> ::String

  def brown: () -> ::String

  def blue: () -> ::String

  def magenta: () -> ::String

  def cyan: () -> ::String

  def gray: () -> ::String
end
