module RbSearch
  # SearchOptions - parses CLI args into settings, generates usage string
  class SearchOptions
    @options: Array[SearchOption]
    @bool_action_dict: Hash[Symbol, Proc]
    @str_action_dict: Hash[Symbol, Proc]
    @int_action_dict: Hash[Symbol, Proc]
    @long_arg_dict: Hash[String, Symbol]

    def initialize: () -> void

    def search_settings_from_args: (Array[String] args) -> SearchSettings

    def settings_from_file: (String file_path, SearchSettings settings) -> void

    def settings_from_json: (String json, SearchSettings settings) -> void

    def usage: () -> void

    def get_usage_string: () -> String

    private

    def set_actions: () -> void

    def set_options_from_json: () -> void
  end
end
