#!/bin/sh

SCALA_VERSION=2.13
SCALASEARCH_VERSION=0.1.0
SCALASEARCH_PATH=$HOME/src/xsearch/scala/scalasearch
# SCALASEARCH_JAR=$SCALASEARCH_PATH/target/scala-$SCALA_VERSION/scalasearch_$SCALA_VERSION-$SCALASEARCH_VERSION.jar
SCALASEARCH_JAR=$SCALASEARCH_PATH/target/scala-$SCALA_VERSION/scalasearch-assembly-$SCALASEARCH_VERSION.jar

# echo "java -Xms1G -Xmx2G -cp $SCALASEARCH_JAR scalasearch.SearchMain $@"
java -Xms1G -Xmx2G -cp $SCALASEARCH_JAR scalasearch.SearchMain $@
