module RbSearch
  # SearchOption - encapsulates a CLI search option
  class SearchOption
    @short_arg: String
    @long_arg: String
    @desc: String
    @arg_type: RbFind::ArgTokenType

    attr_reader short_arg: String
    attr_reader long_arg: String
    attr_reader desc: String
    attr_reader arg_type: RbFind::ArgTokenType

    def initialize: (String short_arg, String long_arg, String desc, RbFind::ArgTokenType arg_type) -> void

    def sort_arg: () -> String
  end
end
