# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rbsearch.gemspec
gemspec

gem 'rake', '~> 13.2.1'

gem 'rbs', '~> 3.9.4'

gem 'test-unit', '~> 3.6.8'

gem 'rubocop', '~> 1.77'

# https://stackoverflow.com/a/19363523/1002072
gem 'rbfind', path: '../../../xfind/ruby/rbfind'

ruby '3.4.4'
