package ktsearch

import ktfind.Color
import ktfind.FileType
import ktfind.FindSettings
import ktfind.SortBy
import java.nio.file.Path
import java.time.LocalDateTime

/**
 * @author cary on 7/23/16.
 */
data class SearchSettings(val archivesOnly: Boolean,
                          val colorize: Boolean,
                          val debug: Boolean,
                          val dirColor: Color,
                          val extColor: Color,
                          val fileColor: Color,
                          val firstMatch: Boolean,
                          val followSymlinks: Boolean,
                          val inArchiveExtensions: Set<String>,
                          val inArchiveFilePatterns: Set<Regex>,
                          val includeHidden: Boolean,
                          val inDirPatterns: Set<Regex>,
                          val inExtensions: Set<String>,
                          val inFilePatterns: Set<Regex>,
                          val inFileTypes: Set<FileType>,
                          val inLinesAfterPatterns: Set<Regex>,
                          val inLinesBeforePatterns: Set<Regex>,
                          val lineColor: Color,
                          val linesAfter: Int,
                          val linesAfterToPatterns: Set<Regex>,
                          val linesAfterUntilPatterns: Set<Regex>,
                          val linesBefore: Int,
                          val maxLastMod: LocalDateTime?,
                          val maxDepth: Int,
                          val maxLineLength: Int,
                          val maxSize: Long,
                          val minDepth: Int,
                          val minLastMod: LocalDateTime?,
                          val minSize: Long,
                          val multiLineSearch: Boolean,
                          val outArchiveExtensions: Set<String>,
                          val outArchiveFilePatterns: Set<Regex>,
                          val outDirPatterns: Set<Regex>,
                          val outExtensions: Set<String>,
                          val outFilePatterns: Set<Regex>,
                          val outFileTypes: Set<FileType>,
                          val outLinesAfterPatterns: Set<Regex>,
                          val outLinesBeforePatterns: Set<Regex>,
                          val paths: Set<Path>,
                          val printDirs: Boolean,
                          val printFiles: Boolean,
                          val printLines: Boolean,
                          val printMatches: Boolean,
                          val printResults: Boolean,
                          val printUsage: Boolean,
                          val printVersion: Boolean,
                          val recursive: Boolean,
                          val searchArchives: Boolean,
                          val searchPatterns: Set<Regex>,
                          val sortBy: SortBy,
                          val sortCaseInsensitive: Boolean,
                          val sortDescending: Boolean,
                          val textFileEncoding: String,
                          val uniqueLines: Boolean,
                          val verbose: Boolean) {
    val findSettings: FindSettings = FindSettings(archivesOnly,
        colorize,
        debug,
        dirColor,
        extColor,
        fileColor,
        followSymlinks,
        inArchiveExtensions,
        inArchiveFilePatterns,
        inDirPatterns,
        inExtensions,
        inFilePatterns,
        inFileTypes,
        searchArchives,
        includeHidden,
        maxDepth,
        maxLastMod,
        maxSize,
        minDepth,
        minLastMod,
        minSize,
        outArchiveExtensions,
        outArchiveFilePatterns,
        outDirPatterns,
        outExtensions,
        outFilePatterns,
        outFileTypes,
        paths,
        printDirs,
        printFiles,
        printUsage,
        printVersion,
        recursive,
        sortBy,
        sortCaseInsensitive,
        sortDescending,
        verbose
    )
}

fun getDefaultSettings() : SearchSettings {
    return SearchSettings(
        archivesOnly = false,
        colorize = true,
        debug = false,
        dirColor = Color.CYAN,
        extColor = Color.YELLOW,
        fileColor = Color.MAGENTA,
        firstMatch = false,
        followSymlinks = false,
        inArchiveExtensions = linkedSetOf(),
        inArchiveFilePatterns = linkedSetOf(),
        includeHidden = false,
        inDirPatterns = linkedSetOf(),
        inExtensions = linkedSetOf(),
        inFilePatterns = linkedSetOf(),
        inFileTypes = linkedSetOf(),
        inLinesAfterPatterns = linkedSetOf(),
        inLinesBeforePatterns = linkedSetOf(),
        lineColor = Color.GREEN,
        linesAfter = 0,
        linesAfterToPatterns = linkedSetOf(),
        linesAfterUntilPatterns = linkedSetOf(),
        linesBefore = 0,
        maxDepth = -1,
        maxLastMod = null,
        maxLineLength = 150,
        maxSize = 0L,
        minDepth = -1,
        minLastMod = null,
        minSize = 0L,
        multiLineSearch = false,
        outArchiveExtensions = linkedSetOf(),
        outArchiveFilePatterns = linkedSetOf(),
        outDirPatterns = linkedSetOf(),
        outExtensions = linkedSetOf(),
        outFilePatterns = linkedSetOf(),
        outFileTypes = linkedSetOf(),
        outLinesAfterPatterns = linkedSetOf(),
        outLinesBeforePatterns = linkedSetOf(),
        paths = linkedSetOf(),
        printDirs = false,
        printFiles = false,
        printLines = false,
        printMatches = false,
        printResults = false,
        printUsage = false,
        printVersion = false,
        recursive = true,
        searchArchives = false,
        searchPatterns = linkedSetOf(),
        sortBy = SortBy.FILEPATH,
        sortCaseInsensitive = false,
        sortDescending = false,
        textFileEncoding = "UTF-8",
        uniqueLines = false,
        verbose = false)
}

fun setArchivesOnly(ss: SearchSettings, archivesOnly: Boolean): SearchSettings {
    return ss.copy(archivesOnly = archivesOnly, searchArchives = archivesOnly || ss.searchArchives)
}
