################################################################################
#
# config.sh
#
# The common configuration for bash scripts
#
################################################################################

########################################
# Configuration
########################################

# XFIND_PATH defaults to $HOME/src/xfind if not defined as env var
if [ -z "$XFIND_PATH" ]; then
    if [ -n "$XFIND_PATH" ]; then
        XFIND_PATH=$XFINDPATH
    else
        XFIND_PATH=$HOME/src/xfind
    fi
fi
source "$XFIND_PATH/scripts/config.sh"


# XSEARCH_PATH defaults to $HOME/src/xsearch if not defined as env var
if [ -z "$XSEARCH_PATH" ]; then
    if [ -n "$XSEARCHPATH" ]; then
        XSEARCH_PATH=$XSEARCHPATH
    else
        XSEARCH_PATH=$HOME/src/xsearch
    fi
fi
XSEARCH_BIN_PATH=$XSEARCH_PATH/bin
XSEARCH_SHARED_PATH=$XSEARCH_PATH/shared
XSEARCH_TEST_FILE_PATH=$XSEARCH_SHARED_PATH/testFiles

# Language roots
XSEARCH_C_PATH=$XSEARCH_PATH/c
XSEARCH_CLOJURE_PATH=$XSEARCH_PATH/clojure
XSEARCH_CPP_PATH=$XSEARCH_PATH/cpp
XSEARCH_CSHARP_PATH=$XSEARCH_PATH/csharp
XSEARCH_DART_PATH=$XSEARCH_PATH/dart
XSEARCH_ELIXIR_PATH=$XSEARCH_PATH/elixir
XSEARCH_FSHARP_PATH=$XSEARCH_PATH/fsharp
XSEARCH_GO_PATH=$XSEARCH_PATH/go
XSEARCH_GROOVY_PATH=$XSEARCH_PATH/groovy
XSEARCH_HASKELL_PATH=$XSEARCH_PATH/haskell
XSEARCH_JAVA_PATH=$XSEARCH_PATH/java
XSEARCH_JAVASCRIPT_PATH=$XSEARCH_PATH/javascript
XSEARCH_KOTLIN_PATH=$XSEARCH_PATH/kotlin
XSEARCH_OBJC_PATH=$XSEARCH_PATH/objc
# XSEARCH_OCAML_PATH=$XSEARCH_PATH/ocaml
XSEARCH_PERL_PATH=$XSEARCH_PATH/perl
XSEARCH_PHP_PATH=$XSEARCH_PATH/php
# XSEARCH_POWERSHELL_PATH=$XSEARCH_PATH/powershell
XSEARCH_PYTHON_PATH=$XSEARCH_PATH/python
XSEARCH_RUBY_PATH=$XSEARCH_PATH/ruby
XSEARCH_RUST_PATH=$XSEARCH_PATH/rust
XSEARCH_SCALA_PATH=$XSEARCH_PATH/scala
XSEARCH_SWIFT_PATH=$XSEARCH_PATH/swift
XSEARCH_TYPESCRIPT_PATH=$XSEARCH_PATH/typescript

# Language version roots
CSEARCH_PATH=$XSEARCH_C_PATH/csearch
CLJSEARCH_PATH=$XSEARCH_CLOJURE_PATH/cljsearch
CPPSEARCH_PATH=$XSEARCH_CPP_PATH/cppsearch
CSSEARCH_PATH=$XSEARCH_CSHARP_PATH/cssearch
DARTSEARCH_PATH=$XSEARCH_DART_PATH/dartsearch
EXSEARCH_PATH=$XSEARCH_ELIXIR_PATH/exsearch
FSSEARCH_PATH=$XSEARCH_FSHARP_PATH/fssearch
GOSEARCH_PATH=$XSEARCH_GO_PATH/gosearch
GROOVYSEARCH_PATH=$XSEARCH_GROOVY_PATH/groovysearch
HSSEARCH_PATH=$XSEARCH_HASKELL_PATH/hssearch
JAVASEARCH_PATH=$XSEARCH_JAVA_PATH/javasearch
JSSEARCH_PATH=$XSEARCH_JAVASCRIPT_PATH/jssearch
KTSEARCH_PATH=$XSEARCH_KOTLIN_PATH/ktsearch
OBJCSEARCH_PATH=$XSEARCH_OBJC_PATH/objcsearch
# OCAMLSEARCH_PATH=$XSEARCH_OCAML_PATH/mlsearch
# MLSEARCH_PATH=$XSEARCH_OCAML_PATH/mlsearch
PLSEARCH_PATH=$XSEARCH_PERL_PATH/plsearch
PHPSEARCH_PATH=$XSEARCH_PHP_PATH/phpsearch
# PS1SEARCH_PATH=$XSEARCH_POWERSHELL_PATH/ps1search
PYSEARCH_PATH=$XSEARCH_PYTHON_PATH/pysearch
RBSEARCH_PATH=$XSEARCH_RUBY_PATH/rbsearch
RSSEARCH_PATH=$XSEARCH_RUST_PATH/rssearch
SCALASEARCH_PATH=$XSEARCH_SCALA_PATH/scalasearch
SWIFTSEARCH_PATH=$XSEARCH_SWIFT_PATH/swiftsearch
TSSEARCH_PATH=$XSEARCH_TYPESCRIPT_PATH/tssearch
