/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("maven-publish")
}

// TODO: replace with use of "com.github.ben-manes.versions" plugin?
apply<DependencyUpdatePlugin>()

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(libs.commons.io)
    implementation(libs.org.json)
    implementation("javafind:lib:0.1.0-SNAPSHOT")
    testImplementation(libs.junit.jupiter)
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.release = 17
}

group = "javasearch" // should this be "xsearch" or "xsearch.javasearch"?
version = "0.1.0-SNAPSHOT"

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
    repositories {
        mavenLocal()
    }
}
