package gosearch

func GetSearchOptions() *SearchOptions {
	return &SearchOptions{
		[]*SearchOption{
			{"a", "allmatches", "Capture all matches*"},
			{"", "archivesonly", "Search only archive files"},
			{"c", "colorize", "Colorize console output*"},
			{"", "debug", "Set output mode to debug"},
			{"e", "encoding", "Set the encoding to use with text files (default: \"utf-8\")"},
			{"", "excludehidden", "Exclude hidden files and directories*"},
			{"1", "firstmatch", "Capture only the first file+pattern match"},
			{"h", "help", "Print this usage and exit"},
			{"", "includehidden", "Include hidden files and directories"},
			{"", "in-archiveext", "Specify extension for archive files to include in search"},
			{"", "in-archivefilepattern", "Specify name pattern for archive files to include in search"},
			{"d", "in-dirpattern", "Specify name pattern for directories to include in search"},
			{"x", "in-ext", "Specify extension for files to include in search"},
			{"f", "in-filepattern", "Specify name pattern for files to include in search"},
			{"t", "in-filetype", "File type to search (text, binary)"},
			{"", "in-linesafterpattern", "Specify pattern to search the \"lines-after\" lines on"},
			{"", "in-linesbeforepattern", "Specify pattern to search the \"lines-before\" lines on"},
			{"L", "linesafter", "Number of lines to include after every matched line (default: 0)"},
			{"", "linesaftertopattern", "Specify pattern to collect lines after up to where pattern matched"},
			{"", "linesafteruntilpattern", "Specify pattern to collect lines after until pattern matched"},
			{"l", "linesbefore", "Number of lines to include before every matched line (default: 0)"},
			{"", "listdirs", "Generate a list of the matching directories after searching"},
			{"", "listfiles", "Generate a list of the matching files after searching"},
			{"", "listlines", "Generate a list of the matching lines after searching"},
			{"", "maxlastmod", "Find files with lastmod less than or equal to maxlastmod"},
			{"w", "maxlinelength", "Max length of line of result to print out (default: 150)"},
			{"", "maxsize", "Find files with size <= maxsize"},
			{"", "minlastmod", "Find files with lastmod greater than or equal to minlastmod"},
			{"", "minsize", "Find files with size >= minsize"},
			{"m", "multilinesearch", "Search files as single multi-line content block"},
			{"C", "nocolorize", "Do not colorize console output"},
			{"P", "noprintmatches", "Suppress printing of search results to stdout"},
			{"R", "norecursive", "Do not search recursively (no subdirectories)"},
			{"Z", "nosearcharchives", "Do not search archive files (bz2, gz, tar, zip)*"},
			{"", "out-archiveext", "Specify extension for archive files to exclude from search"},
			{"", "out-archivefilepattern", "Specify name pattern for archive files to exclude from search"},
			{"D", "out-dirpattern", "Specify name pattern for directories to exclude from search"},
			{"X", "out-ext", "Specify extension for files to exclude from search"},
			{"F", "out-filepattern", "Specify name pattern for files to exclude from search"},
			{"T", "out-filetype", "File type not to search (text, binary)"},
			{"", "out-linesafterpattern", "Specify pattern to filter the \"lines-after\" lines on"},
			{"", "out-linesbeforepattern", "Specify pattern to filter the \"lines-before\" lines on"},
			{"p", "printmatches", "Print search results to stdout*"},
			{"r", "recursive", "Search recursively through subdirectories*"},
			{"s", "searchpattern", "Specify search pattern"},
			{"z", "searcharchives", "Search archive files (bz2, gz, tar, zip)"},
			{"", "settings-file", "A path to a JSON file with specified search settings"},
			{"", "sort-by", "Sort by: PATH, NAME, TYPE, SIZE, LASTMOD"},
			{"", "sort-ascending", "Sort results in ascending order*"},
			{"", "sort-casesensitive", "Sort results case-sensitive*"},
			{"", "sort-caseinsensitive", "Sort results case-insensitive"},
			{"", "sort-descending", "Sort results in descending order"},
			{"u", "uniquelines", "Save only search results with unique lines from previous results"},
			{"v", "verbose", "Set output mode to verbose"},
			{"V", "version", "Print version and exit"},
		},
	}
}
